"""001_control_schema

Revision ID: 28166ec29553
Revises: 
Create Date: 2026-02-27 18:23:32.248420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28166ec29553'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'state_code', name='uq_holiday_date_state'),
    schema='control'
    )
    op.create_index('ix_holidays_year', 'holidays', ['year'], unique=False, schema='control')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INGESTING', 'QA_RUNNING', 'ANALYSIS_RUNNING', 'FORECAST_RUNNING', 'DONE', 'WARN', 'FAILED', name='job_status', schema='control', create_constraint=True), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('meter_id', sa.String(length=100), nullable=True),
    sa.Column('plz', sa.String(length=5), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_phase', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='control'
    )
    op.create_index('ix_jobs_company_id', 'jobs', ['company_id'], unique=False, schema='control')
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False, schema='control')
    op.create_index('ix_jobs_meter_id', 'jobs', ['meter_id'], unique=False, schema='control')
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False, schema='control')
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['control.jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='control'
    )
    op.create_index('ix_files_job_id', 'files', ['job_id'], unique=False, schema='control')
    op.create_index('ix_files_sha256', 'files', ['sha256'], unique=False, schema='control')
    op.create_table('reader_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['control.files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    schema='control'
    )
    op.create_index('ix_reader_profiles_file_id', 'reader_profiles', ['file_id'], unique=False, schema='control')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reader_profiles_file_id', table_name='reader_profiles', schema='control')
    op.drop_table('reader_profiles', schema='control')
    op.drop_index('ix_files_sha256', table_name='files', schema='control')
    op.drop_index('ix_files_job_id', table_name='files', schema='control')
    op.drop_table('files', schema='control')
    op.drop_index('ix_jobs_status', table_name='jobs', schema='control')
    op.drop_index('ix_jobs_meter_id', table_name='jobs', schema='control')
    op.drop_index('ix_jobs_created_at', table_name='jobs', schema='control')
    op.drop_index('ix_jobs_company_id', table_name='jobs', schema='control')
    op.drop_table('jobs', schema='control')
    op.execute("DROP TYPE IF EXISTS control.job_status")
    op.drop_index('ix_holidays_year', table_name='holidays', schema='control')
    op.drop_table('holidays', schema='control')
    # ### end Alembic commands ###
