-- Extensions required by LOAD-GEAR
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Schemas
CREATE SCHEMA IF NOT EXISTS control;
CREATE SCHEMA IF NOT EXISTS analysis;
CREATE SCHEMA IF NOT EXISTS data;
